gperciva/gub

gub/specs/lilypad.py

Building of lilypad requires the aclocal command
contained in an automake package. 
However, automake was not built when building only lilypad. 
Then, automake is added to the dependency of lilypad.

Fix lilypad dependency

---

gub/specs/cygwin/lilypond.py
gub/specs/lilypond.py

lilypond's issue4347 set LDFLAGS to build python modules.
So, GUB can be deleted {mingw|cygwin}::lilypond LDFLAGS libpython.
http://code.google.com/p/lilypond/issues/detail?id=4347
https://codereview.appspot.com/227850044
It has been pushed.
http://git.savannah.gnu.org/gitweb/?p=lilypond.git;a=commit;h=2eb22fd223cd56a2dd90eda1499dadbcbfa5fad5

Delete {mingw|cygwin}::lilypond LDFLAGS libpython for lilypond's issue4347

---

gub/installer.py
gub/specs/fontconfig.py
gub/specs/fonts-bitstream-charter.py
gub/specs/fonts-bitstream-vera.py
gub/specs/fonts-dejavu.py
gub/specs/fonts-ipafont.py
gub/specs/fonts-liberation.py
gub/specs/fonts-libertine.py
gub/specs/fonts-luximono.py
gub/specs/fonts-texgyre.py
gub/specs/fonts-urw-core35.py
gub/specs/libertine-fonts.py
gub/specs/lilypond-doc.py
gub/specs/lilypond-test.py
gub/specs/lilypond.py
patches/fontconfig-2.11.1-new-urw-aliases.patch
patches/fontconfig-2.11.1-texgyre-aliases.patch
sourcefiles/lilypond-sharhead.sh

In association with Issue 4553
https://code.google.com/p/lilypond/issues/detail?id=4553
LilyPond's `make doc' requires some fonts.
So this pull request adding to install them to GUB environment.
Would you merge this?

Install required fonts

---

lilypond.make

lilypond.make's doc and test-output used offline mode.
So dependency files were not downloaded.

Use online mode for lilypond.make's doc and test-output

---

gub/misc.py
gub/specs/fontconfig.py
gub/specs/fonts-gnufreefont.py
gub/specs/fonts-urw-core35.py
gub/specs/glib.py
gub/specs/harfbuzz.py
gub/specs/libffi.py
gub/specs/lilypond-doc.py
gub/specs/lilypond-test.py
gub/specs/pango.py
patches/fontconfig-2.11.1-conf-relative-symlink.patch
patches/glib-2.44.1-darwin-in.patch
patches/glib-2.44.1-darwin-x86-lib-depend.patch
patches/glib-2.44.1-darwin-x86-zlib.patch
patches/glib-2.44.1-mingw-w64-if_nametoindex.patch
patches/pango-1.36.8-substitute-env.patch
patches/pango-1.36.8-test-without-cairo.patch
sourcefiles/pango.modules

Issue 4587
http://lists.gnu.org/archive/html/lilypond-devel/2015-08/msg00324.html
LilyPond 2.19.26 regtests, font-family-override.ly sans font problem will be solved by this patch.
Would you merge it and update local work tree?

Updates to URW fonts and Pango

---

gub/specs/libffi.py
gub/specs/pango.py
patches/libffi-3.2.1-linux-64-libdir.patch
patches/pango-1.37.3-test-without-cairo.patch

Issue 4669
http://sourceforge.net/p/testlilyissues/issues/4669/
On linux-64, libffi is on usr/lib64.
However, libffi.so.6 should be on usr/lib instead of usr/lib64.
This patch will solve this issue.
Would you merge it and try following command before next 2.19.33 `make lilypond'?
```
```

Fix linux-64::libffi

---

README
gub/mirrors.py
gub/misc.py
gub/sources.py
gub/specs/boost.py
gub/specs/cygwin/lilypond.py
gub/specs/darwin/darwin-sdk.py
gub/specs/freebsd-runtime.py
gub/specs/glibc-core.py
gub/specs/glibc.py
gub/specs/hello.py
gub/specs/libgnugetopt.py
gub/specs/libwsock32.py
gub/specs/licoli.py
gub/specs/lilypad.py
gub/specs/lilypond.py
gub/specs/lilypondcairo.py
gub/specs/mingw-extras.py
gub/specs/netpbm.py
gub/specs/osx-lilypad.py
gub/specs/patch.py
gub/specs/regex.py
gub/specs/tcltk.py
gub/specs/texlive.py
gub/versiondb.py
sourcefiles/lilypond-sharhead.sh
sourcefiles/lilypond.README
sourcefiles/sharhead.sh
web/basics.html
web/history.html

lilypond.org/download should serve the website download page
through language negotiation:
https://sourceforge.net/p/testlilyissues/issues/4833/

replace lilypond.org/download with lilypond.org/downloads

---

gub/repository.py
gub/specs/fontconfig.py
gub/specs/freetype.py
gub/specs/ghostscript.py
gub/specs/git.py
gub/specs/harfbuzz.py
gub/specs/imagemagick.py
gub/specs/libpng.py
gub/specs/pango.py

Issue 4876: The wrong font name is embedded by using some OTF / OTC fonts 
https://sourceforge.net/p/testlilyissues/issues/4876/
For avoiding wrong font name, this pull request updates FreeType and some libraries.
Would you merge it and try following command before next `make lilypond'?
```
```

Update FreeType to 2.6.3 etc.

---

gub/specs/texinfo.py

This patch updates texinfo to 6.1.
In my GUB environment, the following commands are succeed.
```
$ bin/gub tools::texinfo
$ bin/gub linux-64::lilypond
$ bin/gub linux-64::lilypond-doc
```

Update texinfo to 6.1

---

gub/specs/guile.py

In my GUB environment, the following command is succeed.
```
$ bin/gub linux-64::guile
```

Remove Guile texi compilation

---

gub/specs/fontconfig.py
gub/specs/freetype.py
gub/specs/guile.py
gub/specs/harfbuzz.py
gub/specs/libffi.py
gub/specs/librestrict.py
librestrict/restrict.c
patches/libffi-3.0.13-includedir.patch
patches/libffi-3.2.1-includedir.patch

This pull request fixes librestrict C99 problem that is reported here.
http://lists.gnu.org/archive/html/lilypond-devel/2016-08/msg00045.html
And, this pull request fixes tools::guile texi compilation problem.
Also, some libraries update is contained.

Fix librestrict C99 and update some libraries

---

gub/specs/fontconfig.py
patches/fontconfig-2.12.1-mac.patch

http://lists.gnu.org/archive/html/lilypond-devel/2016-09/msg00097.html
https://bugs.freedesktop.org/show_bug.cgi?id=97546
Would you merge it and try following command before next `make lilypond'?
```
```

Fix fontconfg cache failure on mac

---

gub/specs/cross/gcc.py
gub/specs/darwin/cross/gcc.py
gub/specs/fontconfig.py
gub/specs/fonts-urw-core35.py
gub/specs/freetype.py
gub/specs/ghostscript.py
gub/specs/lilypond-doc.py
gub/specs/lilypond.py
gub/specs/texinfo.py
gub/specs/zlib.py
patches/fontconfig-2.12.1-fix-psfont-alias.patch
patches/fontconfig-2.12.1-urw-june-2016.patch
patches/ghostscript-9.20-cygwin.patch
patches/ghostscript-9.20-linux-useunix98.patch
patches/ghostscript-9.20-make.patch
patches/ghostscript-9.20-mingw-struct-stat.patch
patches/ghostscript-9.20-mingw-unix-aux.patch
patches/ghostscript-9.20-windows-make.patch
patches/ghostscript-9.20-windows-snprintf.patch

This updates GUB's Ghostscript from 9.15 to 9.20.
gs-9.20 are fixed several font handling bugs and PDF destination name bug etc.
It also includes GCC updates from 4.9.2 to 4.9.4
because GCC 4.9.2 cannot compile some packages in my environment.
Unfortunately, Ghostscript 9.20 for freebsd-x86 raises seg fault.
So for freebsd-x86, Ghostscript 9.15 is used.

Ghostscript 9.20

---

gub/specs/extractpdfmark.py
gub/specs/ghostscript.py
gub/specs/icoutils.py
gub/specs/lilypond-doc.py
gub/specs/lilypond-test.py
gub/specs/lilypond.py
gub/specs/poppler.py

By Issue 5000, optionally using Ghostscript >= 9.20 together with
Extract PDFmark can significantly reduce the disk space required
for building the documentation and the final PDF files.
This pull request makes GUB can use them and reduce the disk space and PDF file size.
It also makes you can use GUB in Ubuntu 16.04 LTS environment.
I've succeeded `make lilypond` clean full building in Ubuntu 16.04 LTS 64 bit environment.
Would you merge this pull request and try following command before next `make lilypond`?
```
```

Use Extract PDFmark

---

gub/specs/ghostscript.py

http://lists.gnu.org/archive/html/lilypond-devel/2016-12/msg00025.html
If I understand correctly, I've found out the cause.
Is there the following line in the log file?
GPL Ghostscript 9.20: Can't find initialization file gs_init.ps.
Would you merge this pull request and try following command before next `make lilypond`?
```
```

Fix tools::ghostscript

---

gub/specs/harfbuzz.py

This patch solves harfbuzz issue.
http://lists.gnu.org/archive/html/lilypond-devel/2016-12/msg00124.html
Would you merge this pull request and try following command before next `make lilypond`?
```
```

Fix harfbuzz when system has ICU

---

gub/specs/fontconfig.py
gub/specs/fonts-texgyre.py
gub/specs/fonts-urw-core35.py
gub/specs/lilypond.py
patches/fontconfig-2.12.1-fix-FcCacheOffsetValid.patch
patches/fontconfig-2.12.1-fix-cache-mingw.patch

This pull request fixes a fontconfig cache issue on Windows.
http://lists.gnu.org/archive/html/lilypond-devel/2017-01/msg00095.html
https://bugs.freedesktop.org/show_bug.cgi?id=99360
The patch has not yet been merged into the fontconfig repository.
However, in order to solve an issue, such as the following, I would like to apply the patch using GUB.
http://lists.gnu.org/archive/html/lilypond-user/2017-02/msg00364.html

Fix fontconfig cache failure on MinGW

---

gub/specs/fonts-urw-core35.py
gub/specs/ghostscript.py
patches/ghostscript-9.21-bug697799-1.patch
patches/ghostscript-9.21-bug697799-2.patch
patches/ghostscript-9.21-bug697846.patch
patches/ghostscript-9.21-bug697892.patch

Ghostscript 9.20 has PNG transparency problem.
http://lists.gnu.org/archive/html/bug-lilypond/2016-12/msg00012.html
https://bugs.ghostscript.com/show_bug.cgi?id=697423
However, on FreeBSD 32 bit, both Ghostscript 9.20 and 9.21 crash.
So only for FreeBSD 32 bit, Ghostscript 9.15 is used.

Update Ghostscript to 9.21

---

gub/specs/texi2html.py

to its location discovered via http://www.nongnu.org/texi2html/texi2html-old.html

www.very-clever.com disappeared - update texi2html URL

---

gub/specs/fonts-ipafont.py

It seems that IPAfont download URL has been changed since June 2016.
http://download.forest.impress.co.jp/pub/library/i/ipafont/10483/IPAfont00303.zip
->
http://dforest.watch.impress.co.jp/library/i/ipafont/10483/IPAfont00303.zip
However, there is a possibility
that it will be changed again by Impress Forest.
So this commit makes GUB downloads it
from CTAN instead of Impress Forest site.

Change fonts-ipafont download site

---

gub/specs/fonts-urw-core35.py

URW++ has been released URW++ core 35 fonts 2017-07-27.
It has some bugfixes.
Issue 5163 can handle URW++ core 35 fonts 2017-07-20 and above.
Would you upload
https://drive.google.com/file/d/0ByGBX3PDrqjsc0VmQlRlaDdOZUk/view?usp=sharing
file as
http://lilypond.org/downloads/gub-sources/urw-fonts/urw-core35-fonts-91edd6e.tar.xz
before merging this PR?

Update urw otf 20170727

---

gub/specs/lilypad.py

This pull request fixes Issue 5177.
https://sourceforge.net/p/testlilyissues/issues/5177/
Would you merge it and upload
https://drive.google.com/file/d/0ByGBX3PDrqjsZkdGd3pWNjlNXzA/view?usp=sharing
as
http://lilypond.org/downloads/gub-sources/lilypad/lilypad-0.1.3.0-src.tar.xz
?

Issue 5177: Update lilypad to 0.1.3.0

---

gub/gup.py
gub/specs/darwin/cross/gcc.py
gub/specs/darwin/odcctools.py
gub/specs/ghostscript.py
gub/specs/git.py
gub/specs/glib.py
gub/specs/glibc.py
gub/specs/libpng.py
gub/specs/lilypond.py
gub/specs/make.py
patches/glib-2.44.1-suppress-string-format-warning.patch
patches/glibc-allow-make4.patch
patches/make_glob2.patch

This patch allows to run `make bootstrap` successfully on Fedora 28, which has gcc version 8.1.1
As you can see, it's built on top of PR #46 (still to be merged)
Issue on LilyPond tracker:
https://sourceforge.net/p/testlilyissues/issues/5424/

Glib patch

---

gub/installer.py
gub/specs/fontconfig.py
gub/specs/lilypond.py

Note that this commit needs lilypond issue #5450 so that we can set up
gub-specific fontconfig configuration files.  As a consequence you can't
test older lilypond versions anymore without patching the created file
`.../target/.../root/usr/etc/relocate/fontconfig.reloc`, replacing `set?`
with `set` (this undoes the use of a special fontconfig setup).
Another minor change is that we no longer generate file
`98-gub-fonts-dir.conf` but `08-gub-fonts-dir.conf`, following fontconfig's
recommendation of include file names.

fontconfig: Avoid access of fonts outside of gub.

---

gub/specs/imagemagick.py

On my openSUSE Leap 42.3 GNU/Linux box, a much newer libpng version than the
one in gub is installed.  Similarly, gub's ImageMagick version is quite old,
not coping with newer libpng versions; in particular, it expects that
FARDATA is defined in `png.h`, which has been removed in newer versions.
Finding the bug (namely, why `/usr/include/png.h` was used inspite of
properly adding a `-I` command line parameter to gcc) was tricky, since
manual compilation always succeeded.  It took me some hours to find out the
strange behaviour of the `C_INCLUDE_PATH` environment variable – `strace`
was my friend...

imagemagick.py: Fix include directory order.

---

gub/specs/guile.py

Tested also on ubuntu 14.04, 16.04 and openSuSE Leap 42.3.
Version 3, based on an analysis of Werner Lemberg.
Signed-off-by: Knut Petersen <knut_petersen@t-online.de>

Fix building of guile on openSuSE Tumbleweed and Ubuntu 18.04

---

gub/specs/m4.py
patches/m4-1.4.18-glibc-change-work-around.patch

Also included a patch taken from Ubuntu to fix issues with recent glibc
versions.
https://bugzilla.redhat.com/show_bug.cgi?id=1573342
After a new release of m4 this patch is no longer necessary since `gnulib`
has already a fix.

m4: Update to 1.4.18.

---

gub/specs/db.py
gub/specs/python.py

Fix building of python 2.4.5 on openSuSE Tumbleweed and ubuntu 18.
Tested also on ubuntu 16.04

Fix python on openSuSE Tumbleweed and ubuntu 18.04

---

gub/specs/lilypond-test.py

Add missing rsync dependency to lilypond-test

lilypond-test depends on tools::rsync

---

gub/2/db.py
gub/3/db.py

The existing imports used for databases do not work on all common systems (e.g., macOS). By using the generic interfaces, Python will choose the fastest available database implementation, falling back to the internal "dumb" implementation as a last resort.
The shortcomings of the current import were brought to my attention upon receiving the following error message on macOS.
```shell
$ bin/gub --help    
Traceback (most recent call last):
File "bin/gub", line 42, in <module>
from gub import buildrunner
File "bin/../gub/buildrunner.py", line 29, in <module>
from gub import cross
File "bin/../gub/cross.py", line 10, in <module>
from gub import repository
File "bin/../gub/repository.py", line 41, in <module>
from gub.db import db
File "bin/../gub/2/db.py", line 3, in <module>
import dbhash …
```

Use generic Python database modules.

---

librestrict/alias.h
librestrict/restrict-exec.c
librestrict/restrict-open.c
librestrict/restrict-stat.c

`librestrict` (source in the top-level directory of GUB) uses C aliases. Darwin (the underlying operating system that macOS is built on) does not support aliases, thus `librestrict` can not currently be compiled on macOS. This commit defines a `safe_alias` macro that smooths over this missing feature by providing the current behavion on non-darwin systems and providing a workaround on darwin systems. The macro is defined in the `alias.h` file inside the librestrict directory.

Enable compiling librestrict on macOS.

---

bin/build-architecture
bin/build-platform
bin/cygwin-packager
bin/gib
bin/gpkg
bin/gub
bin/gub-tester
bin/gupdate
gub.make
gub/distcc.py
gub/runner.py
gub/specs/cygwin/guile.py
gub/specs/fontforge.py
gub/specs/guile.py
gub/specs/lilypond.py
gub/specs/python.py
gub/versiondb.py
gub/with-lock.py
test-lily/cron-builder.py
test-lily/dist-check.py
test-lily/rsync-lily-doc.py
test-lily/rsync-test.py
test-lily/test-binary.py
test-lily/upload.py

With these patches, I'm able to use gub natively on Arch Linux. I verified that the changes still work on LilyDev (based on Debian) and Ubuntu 18.04 LTS

Changes for native build on Arch Linux

---

gub/specs/bison.py
gub/specs/guile.py
gub/specs/lilypond.py
gub/specs/python3.py
lilypond.make
patches/guile-1.8.7-mingw-copysign.patch
sourcefiles/lilypond-sharhead.sh
test-lily/rsync-lily-doc.py
test-lily/rsync-test.py

Note: For future point releases of 2.20.x, just use a version of GUB before these changes are merged.
The changes work (as of now) with branch `dev/hahnjo/cross-mingw` which contains fixes for cross-compilation to mingw. Tested with
```
make LILYPOND_BRANCH=dev/hahnjo/cross-mingw lilypond
```

Prepare for LilyPond 2.21

---

gub/specs/imagemagick.py

This leads to problems on Arch Linux when tools::imagemagick, built
by the system GCC, is executed with an LD_LIBRARY_PATH that includes
GCC libraries from linux-64.

imagemagick: Disable OpenMP parallelization

---

sourcefiles/lilypond-sharhead.sh

As reported at
https://lists.gnu.org/archive/html/lilypond-user/2020-07/msg00119.html
and tracked at
https://gitlab.com/lilypond/lilypond/-/issues/3768,
when the installers are called with qualified path, the --doc option
stops working. David Sumbler diagnosed the problem as an incorrect path
for searching the docs on the website. Fix this by extracting the base
name of $me.
A better fix would be to record the version in the script upon
generation to make it work even when renamed. For now, this seems
good enough.

Fix --doc option of LilyPond UNIX installers
